export const CAROWINDS_FULL_TICKET_PRICE = 77.15;
export const CAROWINDS_MEAL_TICKET_PRICE = 38.15;

export const FIESTA_TEXAS_FULL_TICKET_PRICE = 61.69;
export const FIESTA_TEXAS_MEAL_TICKET_PRICE = 31.38;

export const SIX_FLAGS_FULL_TICKET_PRICE = 63.86;
export const SIX_FLAGS_MEAL_TICKET_PRICE = 31.38;
